[build]
dependencies = ["build", "hatchling"]

[envs.default]
dependencies = [
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
]

[envs.dev]
dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "flake8>=5.0.0",
    "mypy>=1.0.0",
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "django>=4.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/axai_pg"]

[tool.hatch.envs.default]
python = "3.8"

[tool.hatch.envs.dev]
python = "3.8"
features = ["dev"]

[tool.hatch.envs.test]
python = "3.8"
features = ["test"]

[tool.hatch.envs.lint]
python = "3.8"
features = ["lint"]

[tool.hatch.envs.types]
python = "3.8"
features = ["types"] 